spec:
  template:
    spec:
      source:
        repoURL: "{{repo.url}}"
        path: "{{path}}"
      hooks:
        - manifest: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: build-image-{{name}}
              namespace: {{destination.namespace}}
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: HookSucceeded
            spec:
              workflowTemplateRef:
                name: build-docker-image
                clusterScope: true
              arguments:
                parameters:
                  - name: repoUrl
                    value: "git://{{repo.url}}"
                  - name: revision
                    value: "{{targetRevision}}"
                  - name: context
                    value: "{{path}}"