apiVersion : apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: us-central1-docker.pkg.dev/$PROJECT_ID/app-images/test-app:latest
          ports:
          - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "256Mi"
              cpu: "500m"
